"""
SportStrata social content tool.

Generates ready-to-post draft posts into bot/drafts/{date}.md for manual review.
It does NOT post to X — you copy what you want into your own posting workflow.
No X API keys required.

Contents of a digest:
  - Rare / unprecedented highlights (from stat_analyzer)
  - Game of the day (the day's most notable final)
  - Scoreboard roundup (compact list of finals)
  - A fun fact (date-seeded)

Usage:
  python digest.py                  # yesterday's finals
  python digest.py --date 2026-06-13
"""
import argparse
import os
from datetime import date, timedelta

from config import SPORTSTRATA_URL
import database as db
import fun_facts
from tweet_generator import build as build_highlight

DRAFTS_DIR = os.path.join(os.path.dirname(__file__), "drafts")


def _scores_link() -> str:
    return f"{SPORTSTRATA_URL}/#mlb-games"


def game_recap(g: dict) -> str:
    aw, hm = g.get("away_name", "?"), g.get("home_name", "?")
    asc, hsc = g.get("away_score", "?"), g.get("home_score", "?")
    wp, lp = g.get("winning_pitcher", ""), g.get("losing_pitcher", "")
    arm = f"\nW: {wp}   L: {lp}" if wp else ""
    return f"FINAL\n{aw} {asc}, {hm} {hsc}{arm}\n\nBox score & matchup stats: {_scores_link()}"


def game_of_the_day(games: list[dict]) -> dict | None:
    finals = [g for g in games if g.get("away_score") is not None]
    if not finals:
        return None
    return max(finals, key=lambda x: (x.get("away_score", 0) + x.get("home_score", 0)))


def scoreboard(games: list[dict]) -> str | None:
    rows = []
    for g in games:
        if g.get("away_score") is None:
            continue
        rows.append(f"{g.get('away_name','?')} {g.get('away_score')}, {g.get('home_name','?')} {g.get('home_score')}")
    if not rows:
        return None
    return "Today's MLB finals:\n" + "\n".join(rows[:10]) + f"\n\nFull scores: {_scores_link()}"


def fun_fact(d: date) -> str:
    return f"Baseball fact:\n{fun_facts.pick(d)}\n\n{SPORTSTRATA_URL}"


def build_digest(games: list[dict], highlights: list[dict], d: date) -> str:
    out = [f"# SportStrata — draft posts for {d}", "",
           "_Review, edit, and post the ones you want. Generated by bot/digest.py._", ""]

    def block(title: str, text: str | None):
        if not text:
            return
        flag = "  ⚠ over 280" if len(text) > 280 else ""
        out.append(f"## {title}  ({len(text)} chars){flag}")
        out.append("```")
        out.append(text)
        out.append("```")
        out.append("")

    for h in highlights:
        t = build_highlight(h)
        if t:
            block(f"Highlight — {h.get('type')}  ({h.get('player_name','')})", t)

    gd = game_of_the_day(games)
    if gd:
        block("Game of the day", game_recap(gd))
    block("Scoreboard roundup", scoreboard(games))
    block("Fun fact", fun_fact(d))

    if len(out) <= 4:
        out.append("_No finals or highlights for this date._")
    return "\n".join(out)


def main(target: date):
    import data_fetcher as fetcher          # lazy — pulls statsapi only when run
    import stat_analyzer as analyzer
    db.init_db()

    games = fetcher.get_final_games(target)
    highlights: list[dict] = []
    for g in games:
        try:
            box = fetcher.get_boxscore(g["game_id"])
        except Exception:
            continue
        bats = fetcher.extract_batting_lines(box)
        pits = fetcher.extract_pitching_lines(box)
        for line in bats:
            highlights.extend(analyzer.analyze_batting_line(line, g["game_id"], target))
            db.record_combination(line["player_id"], line["player_name"], g["game_id"], target,
                                  line["hits"], line["home_runs"], line["rbi"], line["runs"], line["total_bases"])
        for line in pits:
            highlights.extend(analyzer.analyze_pitching_line(line, g["game_id"], target))
        highlights.extend(analyzer.check_two_grand_slams(bats, g["game_id"], target))

    md = build_digest(games, highlights, target)
    os.makedirs(DRAFTS_DIR, exist_ok=True)
    path = os.path.join(DRAFTS_DIR, f"{target}.md")
    with open(path, "w", encoding="utf-8") as f:
        f.write(md)
    print(f"Wrote {path}  ({len(games)} finals, {len(highlights)} highlights)")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--date", help="Target date YYYY-MM-DD (default: yesterday)")
    args = ap.parse_args()
    target = date.fromisoformat(args.date) if args.date else date.today() - timedelta(days=1)
    main(target)
